### PR TITLE
Cascade delete of database on app deletion

### LINKED ISSUE #57: Create a migration to cascade delete database row on linked app deletion
Currently, deleting an app with a database throws this error upon deleting a row from the `Apps` database:

```
Executing (default): DELETE FROM "Apps" WHERE "id" = 127
Unhandled rejection SequelizeForeignKeyConstraintError: update or delete on table "Apps" violates foreign key constraint "Databases_app_id_fkey" on table "Databases"
```

The foreign key constraint on Database table needs to change to accommodate cascade deletion.

### PR DESCRIPTION
**Pull request by bharatagarwal**
- Adds an on-delete cascade to the foreign key of the Databases table
- Updates deletion logic for apps with database, since cascade will take care of deletion from Databases table

Fixes #57

### CODE REVIEW

**Review by icevans — COMMENTED** [review]
Does this set  things up so that if you delete a database, it also deletes the app associated with that database? That feels wrong to me -- it should be possible to remove a database from an app without deleting the app. I would think what you want is when you delete an app, you also delete the associated database (maybe that is what this does and it just doesn't look like it because of how sequelize works).

But if it does work so that deleting an app deletes the database, I would think you can keep the foreign key constraint -- by deleting the app, you also delete the database, and so there's never a database with an invalid app id key.

**Review by icevans — COMMENTED** [review]
Looks good here.

**Comment by bharatagarwal** [comment]
The way it is right now, deleting an app deletes the linked database.
However, deleting a database directly will still throw a foreign key constraint error. 

If we want to be able to delete a database, we could set `onDelete` for the foreign key constraint on the Apps table to be `SET NULL`

**Comment by jkulton** [comment]
This is only somewhat related, but I wanted to bring it up. I was looking at the models that other day and I'm not sure whether this is just a Sequelize thing but the association seems reversed to me.

```js
// database.js
Database.associate = function(models) {
  Database.hasOne(models.App, {foreignKey: 'databaseId', as: 'app'});
};

// ...

// app.js
App.associate = function(models) {
  App.belongsTo(models.Database, {foreignKey: 'databaseId', as: 'database'});
};
```

This implies to me that databases _have one_ app and apps _belong to_ databases. 🤔 Shouldn't this be the other way around?

**Pull request merged**
